import Navbar from "@/components/Navbar/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";
import { Inter } from "next/font/google";

import Modal from "../components/Modal";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <main className="mt-[70px] flex min-h-screen flex-col items-center justify-start  gap-5 px-2 py-3 md:mt-0">
            {children}
          </main>
          <Modal />
        </body>
      </html>
    </ClerkProvider>
  );
}
