import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "@uploadthing/react/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center justify-start gap-5 " >
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider >
  );
}
